### ISSUE TITLE
Containerize with docker

### ISSUE THREAD

**Issue by Robert-van-Barlingen** [ElliotKillick/rss2newsletter#3]
@ElliotKillick It would be really useful to containerize this project and publish it on dockerhub. I created a pull-request #2 that does exactly that. The only thing you would need to do is create a dockerhub account (if you haven't already done so, create a personal access token and add your username as DOCKERHUB_USERNAME variable and the secret token as DOCKERHUB_TOKEN secret to github. [This link](https://docs.docker.com/build/ci/github-actions/) explains how.

**Comment by Robert-van-Barlingen** [comment]
In the meantime, for anyone who need the container quickly, I pushed it to my account: []https://hub.docker.com/r/robertvanbarlingen/rss2newsletter

If you're using docker compose, then you can use the following code: 
```
services:
  rss2newsletter:
    image: robertvanbarlingen/rss2newsletter
    container_name: rss2newsletter
    restart: unless-stopped
    volumes:
      - ./rss2newsletter.conf:/rss2newsletter/rss2newsletter.conf
      - ./newsletter_template.html:/rss2newsletter/newsletter_template.html
```
